[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 11
style = "bold red"

[[battery.display]]
threshold = 21
style = "bold yellow"

[container]
format = '[â¯ $symbol \[$name\]]($style) '

[dart]
format = "[â¯ $symbol($version )]($style)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "â€¦/"

[docker_context]
format = "[â¯ $symbol$context]($style) "

[git_branch]
format = "[â¯ $symbol$branch(:$remote_branch)]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
modified = "!${count}"

[golang]
format = "[â¯ $symbol($version )]($style)"

[helm]
format = "[â¯ $symbol($version )]($style)"

[java]
format = "[â¯ ${symbol}(${version} )]($style)"

[line_break]
disabled = true

[lua]
format = "[â¯ $symbol($version )]($style)"

[nodejs]
format = "[â¯ $symbol($version )]($style)"

[package]
disabled = true

[python]
format = '[â¯ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
format = "[â¯ $symbol($version )]($style)"
